name: checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install deps
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Check
        run: pnpm check
      - name: Build SvelteKit
        run: pnpm build
