name: checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install deps
        run: npm install
      - name: Build SvelteKit
        run: npm run build

      - name: Lint
        run: npm run lint
      - name: Check
        run: npm run check
      - name: Build SvelteKit
        run: npm run build
